apiVersion: apps/v1
kind: Deployment
metadata:
  name: slowsvc
  namespace: ambassador
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slowsvc
  template:
    metadata:
      labels:
        app: slowsvc
    spec:
      containers:
      - name: slowsvc
        image: aidanhahn/slowsvc:latest
        ports:
          - containerPort: 10001
---
apiVersion: v1
kind: Service
metadata:
  name: slowsvc
  namespace: ambassador
spec:
  selector:
    app: slowsvc
  ports:
  - name: http
    port: 80
    targetPort: 10001
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: slowsvc-slow
  namespace: ambassador
spec:
  prefix: /slow/
  service: slowsvc
  hostname: "*"
  timeout_ms: 8000
  docs:
    path: /endpoint
    display_name: "slow service"
    timeout_ms: 8000
